"""Constants mirrored from the legacy 00_SIGNALduino.pm implementation."""

SDUINO_VERSION = "3.5.7+20250219"
SDUINO_INIT_WAIT_XQ = 1.5
SDUINO_INIT_WAIT = 2.0
SDUINO_INIT_MAXRETRY = 3
SDUINO_CMD_TIMEOUT = 10.0
SDUINO_KEEPALIVE_TIMEOUT = 60
SDUINO_KEEPALIVE_MAXRETRY = 3
SDUINO_WRITEQUEUE_NEXT = 0.3
SDUINO_WRITEQUEUE_TIMEOUT = 2

SDUINO_DISPATCH_VERBOSE = 5
SDUINO_MC_DISPATCH_VERBOSE = 5
SDUINO_MC_DISPATCH_LOG_ID = "12.1"
SDUINO_PARSE_DEFAULT_LENGHT_MIN = 8
SDUINO_GET_CONFIGQUERY_DELAY = 0.75
