#!/usr/bin/env python3
"""Imports the FHEM client module test vectors into tests/data/fhem/.

The RFFHEM repository ships, for every client module, a testData.json holding
raw telegrams, the expected stage 1 string and the expected stage 2 readings.
That makes it the reference for both decoding stages (see ADR-006).

The vectors are vendored into this repository on purpose: the test suite must
not depend on a sibling checkout of RFFHEM being present, and a pinned copy
makes it visible in the diff when upstream expectations change.

Usage:
    python3 tools/fhem_testdata_import.py --rffhem ../RFFHEM
    python3 tools/fhem_testdata_import.py --rffhem ../RFFHEM --module 14_SD_WS
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_MODULES = [
    "14_SD_WS",
    "14_SD_WS07",
    "14_SD_WS09",
    "14_SD_UT",
    "14_SD_BELL",
    "14_SD_AS",
    "14_Hideki",
    "41_OREGON",
    "14_FLAMINGO",
    "10_FS10",
    "10_SD_GT",
    "10_SD_Rojaflex",
    "14_SD_WS_Maverick",
]

TARGET_DIR = Path(__file__).resolve().parent.parent / "tests" / "data" / "fhem"


def _source_revision(rffhem: Path) -> str:
    """Returns the RFFHEM commit the vectors were taken from, or 'unknown'."""
    try:
        result = subprocess.run(
            ["git", "-C", str(rffhem), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def _target_name(module: str) -> str:
    """14_SD_WS -> sd_ws.json"""
    name = module.split("_", 1)[1] if "_" in module else module
    return f"{name.lower()}.json"


def import_module(rffhem: Path, module: str, revision: str) -> bool:
    source = rffhem / "t" / "FHEM" / module / "testData.json"
    if not source.is_file():
        print(f"  skip {module}: {source} not found")
        return False

    with source.open(encoding="utf-8") as handle:
        vectors = json.load(handle)

    document = {
        "_source": {
            "repository": "https://github.com/RFD-FHEM/RFFHEM",
            "path": f"t/FHEM/{module}/testData.json",
            "revision": revision,
            "imported_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "note": "Generated by tools/fhem_testdata_import.py - do not edit by hand.",
        },
        "vectors": vectors,
    }

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    target = TARGET_DIR / _target_name(module)
    with target.open("w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=1)
        handle.write("\n")

    count = _count_vectors(vectors)
    print(f"  {module} -> {target.relative_to(TARGET_DIR.parent.parent.parent)} ({count} vectors)")
    return True


def _count_vectors(node) -> int:
    if isinstance(node, dict):
        if "rmsg" in node and "dmsg" in node:
            return 1
        return sum(_count_vectors(value) for value in node.values())
    if isinstance(node, list):
        return sum(_count_vectors(item) for item in node)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rffhem",
        default="../RFFHEM",
        help="Path to a RFFHEM checkout (default: ../RFFHEM)",
    )
    parser.add_argument(
        "--module",
        action="append",
        help="Import only this module, may be given several times",
    )
    args = parser.parse_args()

    rffhem = Path(args.rffhem).expanduser().resolve()
    if not rffhem.is_dir():
        print(f"RFFHEM checkout not found: {rffhem}", file=sys.stderr)
        return 1

    revision = _source_revision(rffhem)
    modules = args.module or DEFAULT_MODULES
    print(f"Importing from {rffhem} at {revision[:12]}")

    imported = sum(import_module(rffhem, module, revision) for module in modules)
    print(f"{imported} of {len(modules)} modules imported")
    return 0 if imported else 1


if __name__ == "__main__":
    raise SystemExit(main())
